name: Build Test Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test (${{ matrix.os }})

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux
          - os: windows-latest
            target: x86_64-windows
          - os: macos-latest
            target: aarch64-macos

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          mirror: "https://pkg.machengine.org/zig"
          version: 0.14.0-dev.2577+271452d22

      - name: Build and Test
        run: |
          zig build test --verbose
          # For macOS runners, explicitly set the architecture target
          zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseSmall --summary all

      - name: Package Artifacts
        run: |
          mkdir -p escape-the-darkness
          cp -r zig-out/bin/* escape-the-darkness/

          # Use 7z on Windows, zip on Unix
          if [ "${{ runner.os }}" == "Windows" ]; then
            7z a ${{ matrix.target }}-artifact.zip ./escape-the-darkness/*
          else
            zip -r ${{ matrix.target }}-artifact.zip escape-the-darkness
          fi
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-artifact
          path: ${{ matrix.target }}-artifact.zip

  release:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: List downloaded files
        run: ls -R artifacts/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "snapshot-${{ github.run_number }}"
          fail_on_unmatched_files: true
          files: |
            artifacts/x86_64-linux-artifact/x86_64-linux-artifact.zip
            artifacts/x86_64-windows-artifact/x86_64-windows-artifact.zip
            artifacts/aarch64-macos-artifact/aarch64-macos-artifact.zip
