name: Build Test Release

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch (or change to your main branch name)
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest # Use Ubuntu as the base runner
    name: Build and Test

    strategy:
      matrix:
        target: [x86_64-linux, x86_64-windows, x86_64-macos, aarch64-macos]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          mirror: "https://pkg.machengine.org/zig"
          version: 0.14.0-dev.2577+271452d22

      - name: Build and Test
        run: |
          export ZIG_TARGET="${{ matrix.target }}"
          zig build test --verbose  #Added verbose to show build progress
          zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseSmall --summary all

      - name: Package Artifacts
        run: zip -r ${{ matrix.target }}-artifact.zip zig-out/bin

      - name: Upload Artifacts (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-artifact
          path: ${{ matrix.target }}-artifact.zip

  #Optional job to upload releases to github
  release:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Download builds for
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: List downloaded files (Debugging)
        run: ls -R artifacts/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "snapshot-${{ github.run_number }}"
          fail_on_unmatched_files: true
          files: |
            artifacts/x86_64-linux-artifact/x86_64-linux-artifact.zip
            artifacts/x86_64-windows-artifact/x86_64-windows-artifact.zip
            artifacts/x86_64-macos-artifact/x86_64-macos-artifact.zip
            artifacts/aarch64-macos-artifact/aarch64-macos-artifact.zip
